stages:
  - build_image


variables:
  DOCKER_API_IMAGE: "$CI_REGISTRY_IMAGE/beem-api"
  DOCKER_API_TAG: "latest"
  DOCKER_AIRFLOW_IMAGE: "$CI_REGISTRY_IMAGE/beem-airflow"
  DOCKER_AIRFLOW_TAG: "latest"
  DOCKER_BEEGIS_IMAGE: "$CI_REGISTRY_IMAGE/beegis"
  DOCKER_BEEGIS_TAG: "latest"
  DOCKER_MLFLOW_TRACKING_IMAGE: "$CI_REGISTRY_IMAGE/beem-mlflow-tracking"
  DOCKER_MLFLOW_TRACKING_TAG: "latest"




# JOBS
api_image_job:
  stage: build_image
  image: docker:latest
  services: 
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - docker build -t $DOCKER_API_IMAGE:$DOCKER_API_TAG -f src/api/Dockerfile src/api
    - echo $CI_REGISTRY_PASSWORD_WRITE | docker login -u $CI_REGISTRY_USER_WRITE --password-stdin $CI_REGISTRY
    - docker push $DOCKER_API_IMAGE:$DOCKER_API_TAG
  only:
    - /^build-.*$/
  # when: manual


airflow_image_job:
  stage: build_image
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - docker build -t $DOCKER_AIRFLOW_IMAGE:$DOCKER_AIRFLOW_TAG -f src/airflow/Dockerfile src/airflow
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_AIRFLOW_IMAGE:$DOCKER_AIRFLOW_TAG
  only:
    - /^build-.*$/
  # when: manual


beegis_image_job:
  stage: build_image
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - docker build -t $DOCKER_BEEGIS_IMAGE:$DOCKER_BEEGIS_TAG -f src/beegis/Dockerfile src/beegis
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_BEEGIS_IMAGE:$DOCKER_BEEGIS_TAG
  only:
    - /^build-.*$/
  # when: manual


mlflow_tracking_image_job:
  stage: build_image
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker info
    - docker build -t $DOCKER_MLFLOW_TRACKING_IMAGE:$DOCKER_MLFLOW_TRACKING_TAG -f src/mlflow/Dockerfile src/mlflow
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $DOCKER_MLFLOW_TRACKING_IMAGE:$DOCKER_MLFLOW_TRACKING_TAG
  only:
    - /^build-.*$/
  # when: manual